language: csharp
solution: Cervus.sln
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
install:
  - dotnet restore
  - cd Cervus.Web
  - npm install
script:
  - dotnet build
  - dotnet test Cervus.Dummy.Tests/Cervus.Dummy.Tests.csproj
#   - npm test
after_success:
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    - echo dotnet test and npm test succeeded
after_failure:
    - echo dotnet test or npm test failed
