language: csharp
dist: trusty
sudo: false
mono: none
dotnet: 2.0.0
install:
  - dotnet restore
  - cd Cervus.Web
  - npm install
solution: Cervus.sln

# script:
#   - dotnet test
#   - npm test
# after_success:
#   - echo dotnet test and npm test succeeded
# after_failure:
#   - echo dotnet test or npm test failed
